name: test & build

on:
    pull_request:
        branches: ['main']
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x, 25.x]

        steps:
            - uses: actions/checkout@v6

            - uses: pnpm/action-setup@v6

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm

            - name: Install
              run: pnpm i --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Build packages
              run: pnpm run build

            - name: TypeScript check
              run: pnpm run ws:ts

            - name: Circularity check
              run: pnpm run circularity:check

            - name: Lint
              run: pnpm run lint

            - name: Test packages
              run: pnpm test

            - name: Build harness apps
              run: pnpm run harness:build

            - name: Test harness apps
              run: pnpm run harness:test
